config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'

  resources :users
  resources :itineraries do
    resources :comments
    resources :destinations, shallow: true do
      resources :activities
      resources :details
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :destination
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :itinerary
end

app/models/destination.rb
class Destination < ActiveRecord::Base

  belongs_to :itinerary
  has_many :activities
  has_many :details
end

app/models/detail.rb
class Detail < ActiveRecord::Base

  belongs_to :itinerary
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base

  belongs_to :user
  has_many :comments
  has_many :destinations
  has_many :details, :through => :destinations
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password

 has_many :itineraries
 has_many :destinations, :through => :itineraries
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_filter :authorize

  def new    
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.destination_id = params[:destination_id]

    if @activity.save
      redirect_to @activity.destination.itinerary
    else
      render "new"
    end
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to @activity.destination.itinerary
    else
      render "edit"
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    redirect_to @activity.destination.itinerary
    @activity.destroy #Set to nil for sessions, not objects
  end

  private

  def activity_params
    params.require(:activity).permit(
    :destination_id,
    :day_num,
    :name,
    :location,
    :cost,
    :photo_url,
    :notes
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.itinerary_id = params[:itinerary_id]

    @comment.save

    redirect_to itinerary_path(@comment.itinerary)
  end

  def comment_params
    params.require(:comment).permit(
      :author_name,
      :body
      )
  end
end

app/controllers/concerns/landings_controller.rb
class LandingsController < ApplicationController
 def index
 end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_filter :authorize

  def index
    @destinations = Destination.all
  end

  def new
    @destination = Destination.new
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.itinerary_id = params[:itinerary_id]

    if @destination.save
      redirect_to @destination.itinerary
    else
      render "new"
    end
  end

  def update
    @destination = Destination.find(params[:id])

    if @destination.update(destination_params)
      redirect_to @destination.itinerary
    else
      render "edit"
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    redirect_to @destination.itinerary
    @destination.destroy #Set to nil for sessions, not objects
  end

  private

  def destination_params
    params.require(:destination).permit(
      :itinerary_id,
      :city,
      :country,
      :num_of_days
    )
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  before_filter :authorize

  def new
    @detail = Detail.new
  end

  def edit
    @detail = Detail.find(params[:id])
  end

  def create
    @detail = Detail.new(detail_params)
    @detail.destination_id = params[:destination_id]

    if @detail.save
      redirect_to itineraries_path #FIX THIS
    else
      render "new"
    end
  end

  def update
    @detail = Detail.find(params[:id])

    if @detail.update(detail_params)
      redirect_to itineraries_path #FIX THIS
    else
      render "edit"
    end
  end

  def destroy
    @detail = Detail.find(params[:id])
    redirect_to itineraries_path #FIX THIS
    @detail.destroy
  end

  private

  def detail_params
    params.require(:detail).permit(
      :destination_id,
      :accommodation_name,
      :accommodation_address,
      :accommodation_checkin,
      :accommodation_checkout,
      :accommodation_cost,
      :accommodation_notes,
      :user_name,
      :transportation_type,
      :transportation_company_number,
      :transportation_departure_location,
      :transportation_departure_datetime,
      :transportation_arrival_location,
      :transportation_arrival_datetime,
      :transportation_cost
    )
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  before_filter :authorize

  def index
    @itineraries = Itinerary.all
  end

  def new
    @itineraray = Itinerary.new
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @comment = Comment.new
    @comment.itinerary_id = @itinerary_id
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
  end

  def create
    @itinerary = Itinerary.new(itinerary_params)
    @itinerary.user_id = current_user.id

    if @itinerary.save
      redirect_to new_itinerary_destination_path(@itinerary)
    else
      render "new"
    end
  end

  def update
    @itinerary = Itinerary.find(params[:id])

    if @itinerary.update(itinerary_params)
      redirect_to @itinerary.user
    else
      render "edit"
    end
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])
    redirect_to @itinerary.user
    @itinerary.destroy #Set to nil for sessions, not objects


  end

  private

  def itinerary_params
    params.require(:itinerary).permit(
      :user_id,
      :name,
      :photo_url,
      :start_date,
      :end_date,
      :description,
      :public
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #User enters email and password
    #Create new session if they match

    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to("/itineraries")
    else
      redirect_to('/login')
    end
  end

  

  def destroy
    session[:user_id] = nil
    redirect_to('/')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render 'landings/index'
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to itineraries_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.itineraries.destroy
    @user.session.destroy
    @user.destroy #Set to nil for sessions, not objects

    redirect_to ('/')
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :city,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/activities/edit.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="activity-wrap">
  <div id="user-container">
    <div id="user-new">Edit Activity</div>
    <div id="user-form">
      <%= form_for @activity do |f| %>
        <%= f.hidden_field :day_num, value: params[:day_num] %>
        <%= f.text_field :name, :class => "form-field", :placeholder => "Name of Activity", :style => "color:black;" %><br>
        <%= f.text_field :location, :class => "form-field", :placeholder => "Location", :style => "color:black;" %><br>
        <%= f.text_field :cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>
        <%= f.text_field :notes, :class => "form-field", :placeholder => "Notes", :style => "color:black;" %><br>
        <%= f.submit "Save", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="activity-wrap">
  <div id="user-container">
    <div id="user-new">Create an Activity</div>
    <div id="user-form">
      <%= form_for :activity, url: destination_activities_path do |f| %>
        <%= f.hidden_field :day_num, value: params[:day_num] %>
        <%= f.text_field :name, :class => "form-field", :placeholder => "Name of Activity", :style => "color:black;" %><br>
        <%= f.text_field :location, :class => "form-field", :placeholder => "Location", :style => "color:black;" %><br>
        <%= f.text_field :cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>
        <%= f.text_field :notes, :class => "form-field", :placeholder => "Notes", :style => "color:black;" %><br>
        <%= f.submit "Submit Activity", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div id="user-form" style="display:inline; text-align:center; margin-top:0;">
<%= form_for [ @itinerary, @comment ] do |f| %>
    <h3>Add a Comment:</h3>
    <%= f.text_field :author_name, :class => "form-field", :placeholder => "First \& Last", :style => "color:black;" %><br>
    <%= f.text_area :body, :class => "form-field", :placeholder => "Comment", :style => "color:black;" %><br>
    <%= f.submit "Submit", :id => "login-btn" %>

<% end %>
</div>

app/views/destinations/edit.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="destination-wrap">
  <div id="user-container">
    <div id="user-new">Edit Destination</div>
    <div id="user-form">
      <%= form_for @destination, url: destination_path do |f| %>
      <%= f.text_field :city, :class => "form-field", :placeholder => "City", :style => "color:black;" %><br>
      <%= f.text_field :country, :class => "form-field", :placeholder => "Country", :style => "color:black;" %><br>
      <%= f.text_field :num_of_days, :class => "form-field", :placeholder => "Number of Days", :style => "color:black;" %><br>
      <%= f.submit "Edit Destination", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/destinations/new.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="destination-wrap">
  <div id="user-container">
    <div id="user-new">Add a Destination</div>
    <div id="video-caption" style="margin-top:-10px;margin-bottom:20px;">If travelling to multiple cities, add more later.</div>
    <div id="user-form">
      <%= form_for :destination, url: itinerary_destinations_path do |f| %>
      <%= f.text_field :city, :class => "form-field", :placeholder => "City", :style => "color:black;" %><br>
      <%= f.text_field :country, :class => "form-field", :placeholder => "Country", :style => "color:black;" %><br>
      <%= f.text_field :num_of_days, :class => "form-field", :placeholder => "Number of Days", :style => "color:black;" %><br>
      <%= f.submit "Create Destination", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/details/edit.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="detail-wrap">
  <div id="user-container" style="margin-top:10px;">
    <div id="user-new">Edit Travel Details</div>
    <div id="video-caption" style="margin-top:-10px;margin-bottom:20px;">Change accommodation and transportation info:</div>
    <div id="user-form">
      <%= form_for @detail do |f| %>
        <h4>Accommodation Information</h4>
        <%= f.text_field :accommodation_name, :class => "form-field", :placeholder => "Accommodation Name", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_address, :class => "form-field", :placeholder => "Address", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_checkin, :class => "form-field", :placeholder => "Checkin Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_checkout, :class => "form-field", :placeholder => "Checkout Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>

        <h4>Transportation Information</h4>
        <%= f.text_field :transportation_type, :class => "form-field", :placeholder => "Type (Flight/Train/Drive)", :style => "color:black;" %><br>
        <%= f.text_field :transportation_company_number, :class => "form-field", :placeholder => "Company & number (e.g., UA 1005)", :style => "color:black;" %><br>
        <%= f.text_field :transportation_departure_location, :class => "form-field", :placeholder => "Departure Airport/Station", :style => "color:black;" %><br>
        <%= f.text_field :transportation_departure_datetime, :class => "form-field", :placeholder => "Departure Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :transportation_arrival_location, :class => "form-field", :placeholder => "Arrival Airport/Station", :style => "color:black;" %><br>
        <%= f.text_field :transportation_arrival_datetime, :class => "form-field", :placeholder => "Arrival Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :transportation_cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>
        <%= f.submit "Submit Details", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/details/new.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="detail-wrap">
  <div id="user-container" style="margin-top:10px;">
    <div id="user-new">Travel Details</div>
    <div id="video-caption" style="margin-top:-10px;margin-bottom:20px;">Please add the following for a thorough itinerary:</div>
    <div id="user-form">
      <%= form_for :detail, url: destination_details_path do |f| %>
        <h4>Accommodation Information</h4>
        <%= f.text_field :accommodation_name, :class => "form-field", :placeholder => "Accommodation Name", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_address, :class => "form-field", :placeholder => "Address", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_checkin, :class => "form-field", :placeholder => "Checkin Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_checkout, :class => "form-field", :placeholder => "Checkout Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :accommodation_cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>

        <h4>Transportation Information</h4>
        <%= f.text_field :transportation_type, :class => "form-field", :placeholder => "Type (Flight/Train/Drive)", :style => "color:black;" %><br>
        <%= f.text_field :transportation_company_number, :class => "form-field", :placeholder => "Company & number (e.g., UA 1005)", :style => "color:black;" %><br>
        <%= f.text_field :transportation_departure_location, :class => "form-field", :placeholder => "Departure Airport/Station", :style => "color:black;" %><br>
        <%= f.text_field :transportation_departure_datetime, :class => "form-field", :placeholder => "Departure Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :transportation_arrival_location, :class => "form-field", :placeholder => "Arrival Airport/Station", :style => "color:black;" %><br>
        <%= f.text_field :transportation_arrival_datetime, :class => "form-field", :placeholder => "Arrival Date & Time", :style => "color:black;" %><br>
        <%= f.text_field :transportation_cost, :class => "form-field", :placeholder => "Cost", :style => "color:black;" %><br>
        <%= f.submit "Submit Details", :id => "login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/itineraries/_comment.html.erb
  <p><%= comment.body %>
  <br>Created on <b><%= comment.created_at.to_date %></b> ago by <b><%= comment.author_name %></b></p>

app/views/itineraries/edit.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<div id="itinerary-wrap">
  <div id="user-container">
    <div id="user-new">Edit Information</div>
    <div id="user-form">
    <%= form_for @itinerary do |f| %>
        <%= f.text_field :name, :class => "form-field", :placeholder => "Trip Name", :style => "color:black;" %><br>
        <%= f.text_field :photo_url, :class => "form-field", :placeholder => "Trip Photo URL", :style => "color:black;" %><br>
        <%= f.text_field :start_date, :class => "form-field", :placeholder => "Start Month/Day/Year", :style => "color:black;" %><br>
        <%= f.text_field :end_date, :class => "form-field", :placeholder => "End Month/Day/Year", :style => "color:black;" %><br>
        <%= f.text_field :description, :class => "form-field", :placeholder => "Brief Description", :style => "color:black;" %><br>
        <div class="form-field" style="line-height:35px;margin-left:127px;text-align:left;">
        Make trip viewable? <%= f.check_box :public, :class => "form-checkbox"%>
        </div>
        <%= f.submit "Edit Itinerary", :id => "login-btn" %>
    <% end %>
    </div>
  </div>
</div>

app/views/itineraries/show.html.erb
<%= stylesheet_link_tag "style.css" %>

<div id="nav-bar">
  <div id="home">
    <ul>
      <li><%= link_to "R", itineraries_path %></li>
    </ul>
  </div>
  <div id="nav-basic">
    <ul>
      <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
      <li><%= link_to "Create New", new_itinerary_path %></li>
    </ul>
  </div>
</div>

<video autoplay loop muted>
  <source src="https://a0.muscache.com/airbnb/static/Belong_p1_v2.webm" type="video/webm">
  <source src="https://a0.muscache.com/airbnb/static/Belong_p1_v2.mp4" type="video/mp4">
</video>

<div id="video-header-container" style="margin-top:120px">
  <div id="video-header"><%= @itinerary.name %></div>
  <div id="video-caption"><%= @itinerary.start_date %> to <%= @itinerary.end_date %></div>
  <div id="itinerary-description"><%= @itinerary.description %></div>
</div>


<div id="itinerary-container">
<% @itinerary.destinations.each do |destination| %>
  <div class="itinerary-list">
  <h1><%= destination.num_of_days %> Days in <%= destination.city %></h1>

  <% if @itinerary.user_id == current_user.id %>
  <div id="itinerary-btn-container">
    <%= button_to "Edit", edit_destination_path(destination), method: "get", :class => "edit-btn" %>
    <%= button_to "Delete", destination_path(destination), method: :delete, data: {confirm: "Are you sure?"}, :class => "delete-btn" %>
    <% if destination.details == [] && @itinerary.user_id == current_user.id %>
      <br><%= button_to "Add Travel Information", new_destination_detail_path(destination), method: "get", :class => "add-btn" %>
    <% end %>
  </div>
  <% end %>

  <% if destination.details != [] then destination.details.each do |detail| %>

  <div class="detail-list">
    <div class="details">
      <h4>Accommodation</h4>
        <h5><%= detail.accommodation_name %> | <%= detail.accommodation_address %> | <%= detail.accommodation_cost %></h5>
          <p>
          <br>Checkin: <%= detail.accommodation_checkin %>
          <br>
          <br>Checkout: <%= detail.accommodation_checkout %>
          </p>
    </div>

    <div class="details">
      <h4>Getting There</h4>
      <h5><%=  detail.transportation_company_number%> <%= detail.transportation_type %> | <%= detail.transportation_cost %> </h5>
        <p>
        <br>Departing <%= detail.transportation_departure_location %> at <%= detail.transportation_departure_datetime %>
        <br>
        <br>Arriving <%= detail.transportation_arrival_location %> at <%= detail.transportation_arrival_datetime %>
        </p>
    </div>

    <% if @itinerary.user_id == current_user.id %>
    <div>
        <%= link_to "Edit", edit_detail_path(detail), method: "get", :style => "text-decoration:none; color:#3472f7; font-family:'Muli', sans-serif; margin-left:20px;" %> |
        <%= link_to "Delete", detail_path(detail), method: :delete, data: {confirm: "Are you sure?"}, :style => "text-decoration:none; color:#ff3b30; font-family:'Muli', sans-serif; margin-left:5px;" %>
    </div>
    <% end %>

</div>
  <% end %>
<% end %>

<div class="detail-list" style="margin-top:10px; margin-bottom:10px;">
<% (1..destination.num_of_days).each do |day| %>
  <div class="days">
    <h2>Day <%= "#{day}" %></h2>

    <% destination.activities.each do |activity| %>

      <% if activity.day_num == day %>
      <div class="activity">
        <h1><%= activity.name %></h1>
          <p><b>Location:</b> <%= activity.location %><br>
          <b>Cost:</b> <%= activity.cost %><br>
          <b>Notes:</b> <%= activity.notes %></p>

        <% if activity.destination.itinerary.user_id == current_user.id %>
          <%= link_to "Edit", edit_activity_path(activity) %> | <%= link_to "Delete", activity_path(activity), method: :delete, data: {confirm: "Are you sure?"}, :style => "color:#ff3b30;" %>
        <% end %>

      </div>
      <% end %>

    <% end %>

    <% if destination.itinerary.user_id == current_user.id %>
      <%= link_to "Add", new_destination_activity_path(destination, :day_num => day), method: "get", :style => "text-decoration:none; color:#3472f7; font-family:'Muli', sans-serif; margin-left:5px;" %>
    <% end %>

  </div>
  <% end %>

</div>
<% end %>

<%if @itinerary.user_id == current_user.id %>
  <%= link_to "Add Destination", new_itinerary_destination_path(@itinerary), :style => "text-decoration:none; color:#3472f7; font-family:'Muli', sans-serif; margin-left:5px;" %>
<% end %>

  <div class="detail-list">
    <div class="days" style="margin-bottom: -30px;">
      <div class="activity">
        <h2>Comments</h2>
          <%= render partial: 'itineraries/comment', collection: @itinerary.comments %>
        </div>
      </div>

      <%= render partial: 'comments/form' %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rendezvous</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "style.css" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<%= stylesheet_link_tag "style.css" %>

  <div id="nav-bar">
    <div id="home">
      <ul>
        <li><%= link_to "R", itineraries_path %></li>
      </ul>
    </div>
    <div id="nav-basic">
      <ul>
        <li><%= link_to "#{current_user.name}\'s Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Create New", new_itinerary_path %></li>
      </ul>
    </div>
  </div>

<div id="profile-background">
  <div id="user-container">
    <div id="user-new"><%= @user.name %></div>
    <div id="video-caption"><%= @user.city %></div>
    <%= button_to "Edit Profile", edit_user_path, method: "get", :id => "login-btn", style: "margin-left:125px" %>

    <div id="user-new" style="margin-top:40px;">My Rendezvous</div>
    <div id="profile-container" style="width:50%; margin-top:0px; margin-right: 25%;">
      <div class="itinerary-list" style="width:300px;margin-right:350px;">
      <% @user.itineraries.each do |itinerary| %>
      <div class="single-itinerary">
        <h4><%= link_to itinerary.name, itinerary_path(itinerary) %></h4>
        <% if itinerary.photo_url != "" %>
          <img src='<%= itinerary.photo_url %>' style="width:300px;height:60px;border:0px;">
        <% end %>
        <h5><%= itinerary.start_date %> to <%= itinerary.end_date %></h5>
        <h5 style="text-align:left;">Description:</h5>
          <p><%= itinerary.description %></p>
          <br>
          <br>
        <p>Created by: <%= itinerary.user.name %></p>
        <p>Comments (<%= itinerary.comments.size %>)</p>
        <p><%= link_to "Edit", edit_itinerary_path(itinerary), :style => "color:#2c93ff;" %> | <%= link_to "Destroy", itinerary_path(itinerary), method: :delete, data: {confirm: "Are you sure?"}, :style => "color:#ff3b30" %>
        </div>
    <% end %>
    </div>
  </div>
  </div>
</div>